### ISSUE TITLE
Windows API 'QString' has already been set to version 1

### ISSUE THREAD

**Issue by dkeller93** [menpo/menpo3d#16]
This error happens when trying the mesh.view() from the ipython notebook. There is a fix for Linux in the README, but not windows.

**Comment by patricksnape** [comment]
How are you launching the notebook? From the command line? Try setting the environment variables as mentioned:

```
> set QT_API=pyqt
> set ETS_TOOLKIT=qt4
> ipython notebook
```

**Comment by patricksnape** [comment]
You could also try:

```
conda install wxpython
ipython notebook
```

And then in the notebook use `%matplotlib wx` instead of `%matplotlib qt`.

**Comment by dkeller93** [comment]
I tried setting those environment variables before from powershell and it didn't work (got the same error). However when I set the env vars from my bat file, it worked. Thanks!

main3d.py
```
import numpy as np
import menpo3d.io as mio

mesh = mio.import_builtin_asset('james.obj')
viewer = mesh.view()
```

pys.bat
```
set QT_API=pyqt
set ETS_TOOLKIT=qt4
ipython --matplotlib=qt -i main3d.py
```

**Comment by patricksnape** [comment]
OK - thanks! I've updated the README now as well, for Windows users.
