### ISSUE TITLE
Error importing WRL mesh

### ISSUE THREAD

**Issue by mengjiaow** [menpo/menpo3d#34]
Error when importing mesh:
m = m3io.import_mesh('/vol/hci2/Databases/video/BU-3DFE/F0001/F0001_FE04WH_F3D.wrl')

Stack trace:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-256161222da3> in <module>()
----> 2 m = m3io.import_mesh('/vol/hci2/Databases/video/BU-3DFE/F0001/F0001_FE04WH_F3D.wrl')

/vol/atlas/homes/mengjiao/miniconda/envs/normrecov/lib/python2.7/site-packages/menpo3d/io/input/base.pyc in import_mesh(filepath, landmark_resolver, texture_resolver)
     98                    landmark_ext_map=mesh_landmark_types,
     99                    landmark_attach_func=_import_object_attach_landmarks,
--> 100                    importer_kwargs=kwargs)
    101 
    102 

/vol/atlas/homes/mengjiao/miniconda/envs/normrecov/lib/python2.7/site-packages/menpo/io/input/base.pyc in _import(filepath, extensions_map, landmark_resolver, landmark_ext_map, landmark_attach_func, asset, importer_kwargs)
    858     if importer_kwargs is None:
    859         importer_kwargs = {}
--> 860     built_objects = importer_callable(path, asset=asset, **importer_kwargs)
    861 
    862     # landmarks are iterable so check for list precisely

/vol/atlas/homes/mengjiao/miniconda/envs/normrecov/lib/python2.7/site-packages/menpo3d/io/input/mesh/base.pyc in wrl_importer(filepath, asset, texture_resolver, **kwargs)
    127     # Get the Data
    128     polydata = vtk.vtkPolyData.SafeDownCast(mapper_dataset)
--> 129     polydata.Update()
    130 
    131     # We must have point data!

AttributeError: 'vtkCommonDataModelPython.vtkPolyData' object has no attribute 'Update'

**Comment by patricksnape** [comment]
Fixed in 1c385be9a33a7bd5984e453883d473e00d53de8b
