### ISSUE TITLE
unable to view TriMesh

### ISSUE THREAD

**Issue by mengjiaow** [menpo/menpo3d#43]
Currently this fails to show the mesh in the VTK window:
```python
from menpo.shape import TriMesh
tm = TriMesh.init_from_depth_image(x_im)
tm.view(new_figure=True)
```

**Comment by patricksnape** [comment]
Can you view anything else in VTK?

**Comment by mengjiaow** [comment]
Mayavi seems to work fine

**Comment by jabooth** [comment]
So to check, other meshes view OK on your system? How about:
```python
import menpo3d.io as m3io
mesh = m3io.import_builtin_asset.james_obj()
mesh.view()
```

**Comment by mengjiaow** [comment]
I can't view this one either. Seems like only Mayavi is working...

**Comment by patricksnape** [comment]
Can you try making a new env and reinstalling menpo?
