### ISSUE TITLE
Questions of 3D Models in Menpo3D?

### ISSUE THREAD

**Issue by codediner** [menpo/menpo3d#45]
Hi, I am using the menpo3D to display the james.obj in 3D, and it works perfectly, and I want to know if there is also a library which permits us to generate 3D models?

And I find the 3D model of James has a high resolution, can you tell me which equipements you apply to get a realistic 3D model with such a high resolution like this one? Thank you very much for your responses.

**Comment by jabooth** [comment]
> Hi, I am using the menpo3D to display the james.obj in 3D, and it works perfectly, and I want to know if there is also a library which permits us to generate 3D models?

Not sure what you mean by 'generate' - if you have an existing mesh, it can be exported to an `.obj` file using `export_mesh()`.

> And I find the 3D model of James has a high resolution, can you tell me which equipements you apply to get a realistic 3D model with such a high resolution like this one?

That particular mesh was captured from a Di4D camera system: http://www.di4d.com/
We've also had great results with 3DMD: http://www.3dmd.com/

**Comment by codediner** [comment]
Thank you very much for your answers. I will take a look at the camera systems.

**Comment by patricksnape** [comment]
Closing as this question is not directly related to the menpo3d code.

**Comment by lxy2017** [comment]
Hi, I want to use menpo3d to obtain the result of the paper "3D Face Morphable Models “In-the-Wild”. How can I do?

**Comment by patricksnape** [comment]
I believe @jabooth is still working on releasing the publicly ready version of the code
