### ISSUE TITLE
per_vertex_occlusion gives Segmentation fault

### ISSUE THREAD

**Issue by HaoyangWang** [menpo/menpo3d#54]
Hi, I'm trying to extract vertex colour with occlusion, and the following code gives me Segmentation fault:

```
import menpo3d.io as m3io
from menpo3d.extractimage import per_vertex_occlusion

mesh = m3io.import_mesh('/data/body_template/16joints/Male_63119_126226.obj')
mask = per_vertex_occlusion(mesh)
```

I traced back to the source code and this line:

`model_to_image_transform, shape_image = render_hi_res_shape_image(mesh, render_width=render_width)`

in the definition of `per_vertex_occlusion` is causing the error, so I think it's a problem with glrasterizer.

Any suggestions on how to fix this?

**Comment by patricksnape** [comment]
This should be fixed by the change to moderngl
