### ISSUE TITLE
GLRasterizer dll load failure in RasterizationBasics.ipynb

### ISSUE THREAD

**Issue by eosulliv** [menpo/menpo3d#57]
This issue occurs in the 5th cell RasterizationBasics.ipynb in the menpo3d notebooks. 
`from menpo3d.rasterize import GLRasterizer`
`# Build a rasterizer configured from the current view`
`r = GLRasterizer(**viewer_settings)`

The resulting error looks like this:
`ImportError                               Traceback (most recent call last)`
`<ipython-input-7-5266371db03a> in <module>()`
`      3 # Build a rasterizer configured from the current view`
`      4 # r = GLRasterizer(**viewer_settings)`
`----> 5 r = GLRasterizer()`

`~\Anaconda3\envs\menpo\lib\site-packages\cyrasterize\base.py in __init__(self, width, height, model_matrix, view_matrix, projection_matrix, verbose)`
`     98                  view_matrix=None, projection_matrix=None, verbose=False):`
`     99         # delay import so we only check for GL setup at first initialization`
`--> 100         from .glrasterizer import GLRasterizer`
`    101         self._opengl = GLRasterizer(width, height, verbose=int(verbose))`
`    102         if not self._opengl.successfully_initialized():`

`ImportError: DLL load failed: The specified module could not be found.`

My laptop runs a Windows 10 OS and I was wondering if that might be a part of the issue. I've checked that the latest versions of menpo3d and cyrasterize are installed. Would you have any idea what might be causing the error?

**Comment by patricksnape** [comment]
The whole rasterizer has been replaced with moderngl so this shouldn't be an issue anymore
