### ISSUE TITLE
How to export STP/IGES from Mesh or surface ?

### ISSUE THREAD

**Issue by selvakarna** [menpo/menpo3d#65]
How to export STP/IGES from Mesh or surface ?

**Comment by patricksnape** [comment]
Can you export it to obj then use meshlab to convert it? I'm not familiar with those formats

**Comment by selvakarna** [comment]
Hi @patricksnape , are any other cad model?

**Comment by patricksnape** [comment]
I've never used CAD models before so my support here is limited. The [trimesh](https://github.com/mikedh/trimesh) package has support for many file types and may be your best bet trying to get data into Python. What kind of CAD models are you trying to load and what do you expect to be able to do with them?

**Comment by selvakarna** [comment]
I need to export STEP CAD Model from surface? using Python ?

**Comment by selvakarna** [comment]
@patricksnape , trimesh does not have CAD Model generation. [STEP,IGS]...

**Comment by patricksnape** [comment]
A quick google finds this:

https://github.com/guillaume-florent/aoc-xchange

But I have no experience with CAD at all so I'm afraid this is the limit of my help. I'm going to close this out as CAD models are not supported by Menpo3D and there are no plans for support in the future - good luck!
