### ISSUE TITLE
3D Morphable Models

### ISSUE THREAD

**Issue by stephenhermes** [menpo/menpo3d#68]
Hi, has the 3DMM from *3D Face Morphable Models "In-the-Wild"* been implemented in Menpo3d yet? I couldn't find any documentation, nor could I find an implemented model in the codebase. Thanks.

<blockquote>I believe @jabooth is still working on releasing the publicly ready version of the code

_Originally posted by @patricksnape in https://github.com/menpo/menpo3d/issues/45#issuecomment-290937476_</blockquote>

**Comment by jabooth** [comment]
Hey @stephenhermes, sorry for the confusion, the code was released under a separate repository here: https://github.com/menpo/itwmm. That repository is referenced from the journal paper, sorry it wasn't obvious how to find it from the CVPR paper.
