### ISSUE TITLE
Question about menpo3d.io.import_mesh

### ISSUE THREAD

**Issue by YunjieYu** [menpo/menpo3d#69]
Hello, 
    I have a question about the function menpo3d.io.import_mesh. When I use the import_mesh, the returned mesh has 156783 points(`mesh.points.shape == (156783, 3)`), but actually my obj file has only 26317 points. The two are not equal. Can someone tell me why this happens? 
Thanks in advance!

**Comment by mhwu2017** [comment]
I have the same question. Did you solve it?
